version: 2
updates:
    - package-ecosystem: "npm"
        directory: "/apps/nt-stylesheet"
        schedule:
            interval: "daily"
        open-pull-requests-limit: 5
        assignees:
            - "khoilen"
