packages:
    - apps/*
    - packages/*
catalog:
    '@commitlint/cli': 20.1.0
    '@commitlint/config-conventional': 20.0.0
    '@eslint/eslintrc': 3.3.1
    '@mdi/font': 7.4.47
    '@nx/storybook': 22.1.3
    '@nx/vite': 22.1.3
    '@nx/web': 22.1.3
    '@radix-ui/react-avatar': 1.1.2
    '@radix-ui/react-checkbox': 1.1.3
    '@radix-ui/react-collapsible': 1.1.3
    '@radix-ui/react-dialog': 1.1.6
    '@radix-ui/react-popover': 1.1.6
    '@radix-ui/react-progress': 1.1.2
    '@radix-ui/react-select': 2.1.6
    '@radix-ui/react-separator': 1.1.2
    '@radix-ui/react-slot': 1.1.2
    '@radix-ui/react-tooltip': 1.1.8
    '@storybook/addon-actions': 8.4.7
    '@storybook/addon-essentials': 8.4.7
    '@storybook/addon-interactions': 8.4.7
    '@storybook/manager-api': 8.5.2
    '@storybook/nextjs': 8.4.7
    '@storybook/react': 8.4.7
    '@storybook/theming': 8.5.2
    '@tanstack/react-table': 8.21.2
    '@testing-library/jest-dom': 6.6.3
    '@testing-library/react': 16.3.0
    '@testing-library/user-event': 14.6.1
    '@trivago/prettier-plugin-sort-imports': 5.2.1
    '@types/node': 22.14.0
    '@types/react': 19.0.0
    '@types/react-dom': 19.0.0
    '@typescript-eslint/eslint-plugin': 8.48.1
    '@typescript-eslint/parser': 8.48.1
    '@vitejs/plugin-react': 4.3.4
    '@vitest/coverage-v8': 4.0.15
    '@storybook/addon-docs': 10.1.4
    '@storybook/nextjs-vite': 10.1.4
    '@chromatic-com/storybook': 4.1.3
    '@storybook/addon-links': 10.1.4
    autoprefixer: 10.4.20
    brace-expansion: 4.0.1
    chart.js: 4.4.8
    class-variance-authority: 0.7.1
    clsx: 2.1.1
    cmdk: 1.0.4
    cpx: 1.5.0
    cssnano: 7.0.6
    dompurify: 3.2.6
    eslint: 9.17.0
    eslint-config-prettier: 10.1.1
    eslint-formatter-pretty: 6.0.1
    eslint-plugin-jsonc: 2.20.0
    eslint-plugin-jsx-a11y: 6.10.2
    eslint-plugin-prettier: 5.2.6
    eslint-plugin-react: 7.37.5
    eslint-plugin-testing-library: 7.1.1
    eslint-plugin-unused-imports: 4.1.4
    http-server: 14.1.1
    husky: 9.0.11
    jsdom: 26.0.0
    lint-staged: 13.2.3
    lucide-react: 0.474.0
    minimatch: 8.0.0
    next: 16.0.10
    npm-package-json-lint: 8.0.0
    nx: 22.1.3
    postcss: 8.5.3
    postcss-import: 16.1.0
    postcss-nesting: 13.0.1
    postcss-preset-env: 10.2.4
    postcss-reporter: 7.1.0
    prettier: 3.0.1
    react: 19.0.0
    react-chartjs-2: 5.3.0
    react-dom: 19.0.0
    rollup: 4.46.2
    sass: 1.88.0
    sass-embedded: 1.83.4
    storybook: 10.1.10
    stylelint: 16.19.1
    stylelint-config-standard-scss: 14.0.0
    stylelint-config-tailwindcss: 1.0.0
    stylelint-prettier: 5.0.3
    stylelint-scss: 6.11.1
    tailwind-merge: 2.6.0
    tailwindcss: 3.4.17
    tailwindcss-animate: 1.0.7
    typescript: 5.7.2
    vite: 6.4.1
    vite-bundle-visualizer: 1.2.1
    vite-plugin-dts: 4.5.0
    vite-plugin-sass-dts: 1.3.29
    vitest: 4.0.15
    vitest-canvas-mock: 0.3.3
    eslint-plugin-storybook: 10.1.10
