name: Publish Coverage

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    publish-coverage:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write

        strategy:
            matrix:
                include:
                    - name: 'Style Sheet'
                      app: 'nt-stylesheet'
                    - name: 'Headless UI'
                      app: 'nt-headless-ui'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9.15.3
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.18.2
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run tests
              run: pnpm run test --coverage

            - name: Report Coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                  name: ${{ matrix.name }}
                  json-summary-path: ./apps/${{ matrix.app }}/coverage/coverage-summary.json
                  json-final-path: ./apps/${{ matrix.app }}/coverage/coverage-final.json
