name: Publish Coverage

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    publish-coverage:
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write

        strategy:
            matrix:
                include:
                    - name: 'Style Sheet'
                      app: 'nt-stylesheet'
                    - name: 'Headless UI'
                      app: 'nt-headless-ui'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  clean: true
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.18.2

            - name: Check and Install pnpm
              run: |
                  if ! command -v pnpm &> /dev/null
                  then
                    echo "pnpm not found, installing..."
                    npm install -g pnpm@9.15.3
                  else
                    echo "pnpm is already installed."
                  fi
                    echo "checking pnpm version..."
                  pnpm -v

            - name: Cache pnpm store
              uses: actions/cache@v3
              with:
                  path: ${{ github.workspace }}/.pnpm-store
                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                      pnpm-store-${{ runner.os }}-
                      pnpm-store-

            - name: Install dependencies
              run: pnpm install --store-dir=${{ github.workspace }}/.pnpm-store --node-linker=hoisted --frozen-lockfile

            - name: Run tests
              run: pnpm run test --coverage

            - name: Report Coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                  name: ${{ matrix.name }}
                  json-summary-path: ./apps/${{ matrix.app }}/coverage/coverage-summary.json
                  json-final-path: ./apps/${{ matrix.app }}/coverage/coverage-final.json
