name: Publish Coverage

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    setup-node:
        uses: nashtech-garage/nt-sketchbook/.github/workflows/setup-node.yml@feat/pr-check-pkg

    publish-coverage:
        needs: setup-node
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write

        strategy:
            matrix:
                include:
                    - name: 'Style Sheet'
                      app: 'nt-stylesheet'
                    - name: 'Headless UI'
                      app: 'nt-headless-ui'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Run tests
              run: pnpm run test --coverage

            - name: Report Coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                  name: ${{ matrix.name }}
                  json-summary-path: ./apps/${{ matrix.app }}/coverage/coverage-summary.json
                  json-final-path: ./apps/${{ matrix.app }}/coverage/coverage-final.json
