name: Publish and Release headless-ui

permissions:
    id-token: write
    contents: write
    packages: write
    pull-requests: write

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version bump type'
                required: true
                default: 'patch'
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    call-reusable:
        uses: nashtech-garage/nt-sketchbook/.github/workflows/publish-and-release-reusable.yml@main
        with:
            version: ${{ inputs.version }}
            projectName: 'headless-ui'
            workingDir: 'apps/nt-headless-ui'
            releasePrefix: 'headless-ui'
