name: Publish and Release headless-ui

permissions:
    contents: read

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version bump type'
                required: true
                default: 'patch'
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    call-reusable:
        uses: ./.github/workflows/publish-and-release-reusable.yml
        with:
            version: ${{ inputs.version }}
            projectName: 'headless-ui'
            workingDir: 'apps/nt-headless-ui'
            releasePrefix: 'headless-ui'
        secrets:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
