name: Publish and Release headless-ui

permissions:
    id-token: write
    contents: write
    packages: write
    pull-requests: write

on:
    workflow_dispatch:
        inputs:
            project:
                description: 'Select package to release'
                required: true
                type: choice
                options:
                    - headless-ui
                    - stylesheet
            version:
                description: 'Version bump type'
                required: true
                default: 'patch'
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    call-reusable:
        uses: nashtech-garage/nt-sketchbook/.github/workflows/auto-bump-version.yml@main
        with:
            version: ${{ inputs.version }}
            projectName: ${{ inputs.project }}
            workingDir: ${{ fromJSON('{"headless-ui":"apps/nt-headless-ui","stylesheet":"apps/nt-stylesheet"}')[inputs.project] }}
