name: Publish and Bump version

permissions:
    id-token: write
    contents: write
    packages: write
    pull-requests: write

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version bump type'
                required: true
                default: 'patch'
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    bump-stylesheet:
        name: Bump stylesheet
        uses: nashtech-garage/nt-sketchbook/.github/workflows/auto-bump-version.yml@main
        with:
            version: ${{ inputs.version }}
            projectName: stylesheet
            workingDir: apps/nt-stylesheet

    bump-headless-ui:
        name: Bump headless-ui
        uses: nashtech-garage/nt-sketchbook/.github/workflows/auto-bump-version.yml@main
        with:
            version: ${{ inputs.version }}
            projectName: headless-ui
            workingDir: apps/nt-headless-ui
